# Generated by Django 5.1.4 on 2025-01-10 07:35

import admin_panel.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_alter_user_managers_course_restored_at_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', admin_panel.manager.CustomUserManager()),
            ],
        ),
        migrations.RenameField(
            model_name='coursemodules',
            old_name='parnet_module',
            new_name='parent_module',
        ),
    ]
