# Generated by Django 5.1.4 on 2025-01-13 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_alter_coursemodules_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='joining_date',
            field=models.DateField(blank=True, null=True, verbose_name='joining date'),
        ),
        migrations.AlterField(
            model_name='coursemodulelessons',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='admin_panel.course'),
        ),
        migrations.AlterField(
            model_name='coursemodulelessons',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='admin_panel.coursemodules'),
        ),
    ]
