# Generated by Django 5.1.4 on 2025-01-16 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0009_user_joining_date_alter_coursemodulelessons_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employee_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='employee id'),
        ),
    ]
