# Generated by Django 5.1.4 on 2025-01-17 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0010_user_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='employee_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='employee id'),
        ),
    ]
