# Generated by Django 5.1.4 on 2025-01-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0012_coursecollection'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecollection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='course_collections/'),
        ),
    ]
