# Generated by Django 5.1.4 on 2025-01-20 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0014_alter_coursecollection_image_usercoursesenrolled'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='enrolled_collections',
            field=models.ManyToManyField(blank=True, related_name='enrolled_users', to='admin_panel.coursecollection'),
        ),
        migrations.AlterField(
            model_name='usercoursesenrolled',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.coursecollection'),
        ),
    ]
