# Generated by Django 5.1.4 on 2025-01-21 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0016_usercoursesenrolled_assigned_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecollection',
            name='alloted_time',
            field=models.IntegerField(default=150, verbose_name='alloted time'),
            preserve_default=False,
        ),
    ]
