# Generated by Django 5.1.4 on 2025-01-22 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0019_alter_usercourseprogress_completed_on_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercoursesenrolled',
            old_name='completed',
            new_name='is_completed',
        ),
    ]
