# Generated by Django 5.1.4 on 2025-01-22 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0020_rename_completed_usercoursesenrolled_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourseprogress',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='admin_panel.coursemodulelessons'),
        ),
        migrations.AlterField(
            model_name='usercourseprogress',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='admin_panel.coursemodules'),
        ),
    ]
