# Generated by Django 5.1.4 on 2025-01-27 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0021_alter_usercourseprogress_lesson_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_user', to='admin_panel.coursecollection'),
        ),
    ]
