# Generated by Django 5.1.4 on 2025-02-03 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0023_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercoursesenrolled',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_users_collection', to='admin_panel.coursecollection'),
        ),
    ]
