# Generated by Django 5.1.4 on 2025-02-04 13:56

import admin_panel.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0024_alter_usercoursesenrolled_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=admin_panel.utils.rename_file),
        ),
    ]
