# Generated by Django 5.1.4 on 2025-02-10 10:27

import admin_panel.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0025_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=admin_panel.utils.rename_file),
        ),
    ]
