# Generated by Django 5.1.4 on 2025-02-11 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0027_user_is_verified'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='employee_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='employee id'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('employee_id', 'created_by'), name='unique_employee_per_creator'),
        ),
    ]
