# Generated by Django 5.1.4 on 2025-02-11 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0028_alter_user_employee_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='enrolled_collections',
            field=models.ManyToManyField(blank=True, null=True, related_name='enrolled_users', to='admin_panel.coursecollection'),
        ),
    ]
