# Generated by Django 5.1.4 on 2025-02-11 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0029_alter_user_enrolled_collections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodules',
            name='parent_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_modules', to='admin_panel.coursemodules', verbose_name='parent module'),
        ),
    ]
