# Generated by Django 5.1.4 on 2025-02-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0030_alter_coursemodules_parent_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='enrolled_collections',
            field=models.ManyToManyField(blank=True, related_name='enrolled_users', to='admin_panel.coursecollection'),
        ),
    ]
